# Generated by Django 4.1.1 on 2022-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('size', models.TextField()),
                ('images', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
